apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-chatbot-framework-frontend
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: frontend.dev.ai-chatbot.opsly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opsly-dev-ai-chatbot-framework-frontend
                port:
                  name: http-frontend
  tls:
    - hosts:
        - frontend.dev.ai-chatbot.opsly.local
      secretName: ai-chatbot-framework-dev-tls
